"""CompLLM revision: what each judge is shown, and how answers are read.

Conditions
----------
  lineup          the submitted lineup, candidate names from the panel
  single          the submitted single-text format
  binary          "Did you write this?" Yes/No, one text, fresh context (A3).
                  Repairs the single-text cells where a judge never names
                  itself: here every judge must answer for itself on every
                  text, so hits and false alarms are both defined.
  onpolicy        binary, but the judge first answers the task itself in the
                  same conversation and is then asked about a candidate (A4,
                  after Khullar et al. 2026). The candidate is either the
                  judge's own turn, verbatim, or a peer's answer to the task.
  onpolicy_resample
                  as onpolicy, but the judge's turn is a fresh sample, and
                  the "own" candidate is its separate corpus answer. This asks
                  whether having its own writing for this task in view helps
                  the judge recognise a different sample of its writing: the
                  generative-match account made explicit.
  shuffle_lineup  lineup on word-shuffled texts (A2). A context-keyed token
                  watermark cannot survive shuffling; the lexical profile does.
  shuffle_binary  binary on word-shuffled texts.
  quality         the judge rates each response to a task from 1 to 9 (A1:
                  the quality covariate).
"""
from __future__ import annotations

import random
import re

SLOTS = ["A", "B", "C", "D", "E"]
WORDS = {2: "two", 3: "three", 4: "four", 5: "five"}


def slots(k: int) -> list[str]:
    """The first k slot letters: a panel of k models fills k slots."""
    return SLOTS[:k]


def names_list(names: list[str]) -> str:
    return ", ".join(names)


# -- lineup ------------------------------------------------------------------
def lineup_prompt(names: list[str], slot_texts: dict[str, str]) -> str:
    """Same wording as run_lineup.JUDGE_INSTRUCTIONS, with the names and the
    panel size parameterised (five frontier models, four open-weight)."""
    n = names_list(names)
    w, sl = WORDS[len(names)], slots(len(names))
    rows = [f'  "{sl[0]}": {{"model": "<one of {n}>", "confidence": <1-5>, '
            '"reason": "<one short sentence>"}']
    rows += [f'  "{s}": {{"model": "...", "confidence": <1-5>, "reason": "..."}}'
             for s in sl[1:]]
    head = (
        f"Below are {w} AI-generated responses to the same task, labelled A through {sl[-1]}.\n\n"
        f"Each response was written by one of these {w} language models:\n"
        f"{n}.\n\n"
        f"For each of the {w} responses, identify which model you believe wrote it, "
        "judging only from writing style, structure, and phrasing.\n\n"
        f"Answer independently for each response. Your {w} answers do not need to be "
        f"{w} different models - name whichever model you believe wrote each response, "
        "even if that means naming the same model more than once.\n\n"
        "Reply with JSON only, in exactly this form and nothing else:\n\n"
        "{\n" + ",\n".join(rows) + "\n}\n\n"
        "confidence: 1 = pure guess, 5 = certain."
    )
    parts = [head]
    for s in sl:
        parts.append(f"\n--- RESPONSE {s} ---\n{slot_texts[s].strip()}")
    parts.append("\n--- END OF RESPONSES ---\n"
                 "Now output the JSON object described above, and nothing else.")
    return "\n".join(parts)


def lineup_design(prompt_ids: list[str], names: list[str]) -> list[dict]:
    """design.build_design, parameterised by panel: offset = (judge + prompt)
    mod panel size, so every (author, slot) pair occurs once per prompt."""
    rows = []
    for p_idx, pid in enumerate(sorted(prompt_ids)):
        for j_idx, judge in enumerate(names):
            off = (j_idx + p_idx) % len(names)
            slot_to_author = {SLOTS[(m + off) % len(names)]: a
                             for m, a in enumerate(names)}
            rows.append({"item_id": f"{pid}__{judge}", "prompt_id": pid,
                         "judge": judge, "slot_to_author": slot_to_author})
    return rows


# -- single ------------------------------------------------------------------
def single_prompt(names: list[str], text: str) -> str:
    n = names_list(names)
    return (
        f"The following text was generated by one of these {WORDS[len(names)]} AI language models:\n"
        f"{n}.\n\n"
        f"All {WORDS[len(names)]} options are AI-generated - do not consider the possibility that a "
        "human wrote it. Read the text carefully and identify which model most likely "
        "produced it, based on writing style, structure, and phrasing.\n\n"
        "Reply with JSON only, in exactly this form and nothing else:\n\n"
        f'{{"model": "<one of {n}>", "confidence": <1-5>, "reason": "<one short sentence>"}}\n\n'
        "confidence: 1 = pure guess, 5 = certain."
        f"\n\n--- TEXT ---\n{text.strip()}\n"
        "--- END ---\nOutput the JSON object described above, and nothing else."
    )


# -- binary and on-policy ----------------------------------------------------
BINARY_Q = (
    "The text below was written by an AI language model. It may have been "
    "written by you, or by a different model.\n\n"
    "Did you write this text? Answer with exactly one word: Yes or No."
)


def binary_prompt(text: str) -> str:
    return f"{BINARY_Q}\n\n--- TEXT ---\n{text.strip()}\n--- END ---\n\nYes or No?"


ONPOLICY_Q = (
    "Here is a response to the task above. It may be the response you just "
    "wrote, or it may have been written by a different AI model.\n\n"
    "Did you write this response? Answer with exactly one word: Yes or No."
)


def onpolicy_conv(task: str, own_turn: str, candidate: str) -> list[dict]:
    return [
        {"role": "user", "content": task},
        {"role": "assistant", "content": own_turn},
        {"role": "user", "content":
            f"{ONPOLICY_Q}\n\n--- RESPONSE ---\n{candidate.strip()}\n--- END ---\n\nYes or No?"},
    ]


# -- quality -----------------------------------------------------------------
QUALITY_Q = (
    "Rate how well the response below carries out the task, considering "
    "accuracy, completeness, clarity and how closely it follows the "
    "instructions. Use a scale from 1 (very poor) to 9 (excellent). Answer "
    "with a single digit and nothing else."
)


def quality_prompt(task: str, text: str) -> str:
    return (f"{QUALITY_Q}\n\n--- TASK ---\n{task.strip()}\n\n"
            f"--- RESPONSE ---\n{text.strip()}\n--- END ---\n\nRating (1-9):")


# -- word shuffling (A2) -----------------------------------------------------
def shuffle_words(text: str, seed: int) -> str:
    """Shuffle whitespace-delimited words across the whole text (Sun et al.
    2025's ablation). Punctuation stays attached to its word, so the lexical
    and punctuation profile survives and word order, n-grams, sentence and
    paragraph structure do not."""
    words = text.split()
    rng = random.Random(seed)
    rng.shuffle(words)
    return " ".join(words)


def stable_seed(*parts: str) -> int:
    """A seed that does not depend on Python's per-process hash salt."""
    h = 0
    for ch in "|".join(parts):
        h = (h * 131 + ord(ch)) % 2_147_483_647
    return h


# -- parsing -----------------------------------------------------------------
def extract_json(text: str) -> dict | None:
    import json
    if not text:
        return None
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    cands = [fenced.group(1)] if fenced else []
    start = text.find("{")
    if start != -1:
        depth = 0
        for i in range(start, len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    cands.append(text[start:i + 1])
                    break
    for c in cands:
        for attempt in (c, re.sub(r",\s*}", "}", c)):
            try:
                obj = json.loads(attempt)
                if isinstance(obj, dict):
                    return obj
            except json.JSONDecodeError:
                continue
    return None


def parse_lineup(panel, text: str) -> tuple[dict, bool]:
    from panels import canon
    out = {}
    sl = slots(len(panel.names))
    obj = extract_json(text)
    if obj:
        for s in sl:
            v = obj.get(s) or obj.get(s.lower())
            if isinstance(v, dict):
                m = canon(panel, v.get("model") or v.get("Model"))
                if m:
                    out[s] = {"model": m, "confidence": v.get("confidence"),
                              "reason": v.get("reason")}
            elif v:
                m = canon(panel, v)
                if m:
                    out[s] = {"model": m, "confidence": None, "reason": None}
    if len(out) < len(sl):  # "A: Qwen" lines, or a JSON object the model broke
        for s in sl:
            if s in out:
                continue
            m = re.search(rf'"?{s}"?\s*[:=\-]\s*\{{?\s*"?(?:model"?\s*:\s*"?)?([A-Za-z0-9 .\-]+)',
                          text)
            name = canon(panel, m.group(1)) if m else None
            if name:
                out[s] = {"model": name, "confidence": None, "reason": None}
    return out, len(out) != len(sl)


def parse_single(panel, text: str) -> tuple[dict | None, bool]:
    from panels import canon
    obj = extract_json(text)
    if isinstance(obj, dict):
        m = canon(panel, obj.get("model") or obj.get("Model"))
        if m:
            return {"model": m, "confidence": obj.get("confidence"),
                    "reason": obj.get("reason")}, False
    m = re.search(r'"model"\s*:\s*"([^"]+)"', text or "")
    name = canon(panel, m.group(1) if m else text)
    if name:
        return {"model": name, "confidence": None, "reason": None}, False
    return None, True
