"""Write paper_tacl/numbers_rev.tex from the revision's results JSON.

    python paper_tacl/make_numbers.py

Every number the TACL draft states that is not already in paper/numbers.tex
(the submitted study's macros, still generated by src/engine_b.py) comes from
here, so prose and results cannot drift apart. Missing inputs produce
\\PENDING{...} markers instead of numbers, which render in red.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "numbers_rev.tex"
lines = ["% GENERATED by paper_tacl/make_numbers.py -- do not edit by hand.",
         r"\providecommand{\PENDING}[1]{\textcolor{red}{[#1]}}"]


def mac(name: str, val: str) -> None:
    lines.append(rf"\newcommand{{\{name}}}{{{val}}}")


def pct(x: float, d: int = 1) -> str:
    return f"{100 * x:.{d}f}\\%"


def pp(x: float) -> str:
    return f"{100 * x:+.1f}".replace("-", "$-$")


def ci(lo: float, hi: float, unit: str = "pp") -> str:
    f = (lambda v: f"{100 * v:+.1f}") if unit == "pp" else (lambda v: f"{100 * v:.1f}")
    return f"[{f(lo)}, {f(hi)}]".replace("-", "$-$")


def pval(p: float) -> str:
    if p < 0.001:
        return f"{p:.1e}".replace("e-0", r"\times10^{-").replace("e-", r"\times10^{-") + "}"
    return f"{p:.3f}"


# ---------------------------------------------------------------------------
# Study 1: frontier panel, re-analysed (results/stats_revision.json)
# ---------------------------------------------------------------------------
S = json.loads((ROOT / "results" / "stats_revision.json").read_text())
cond_tag = {"lineup": "Lineup", "single": "Single"}
for cond, tag in cond_tag.items():
    for j, g in S[cond]["per_judge"].items():
        sa = g["self_advantage"]
        mac(f"{j}Adv{tag}CI", ci(*sa["ci_cluster"]))
        mac(f"{j}Adv{tag}P", "$" + pval(sa["randomization"]["p_exact"]) + "$")
        mac(f"{j}Adv{tag}Holm", "$" + pval(sa["p_holm_randomization"]) + "$")
        mac(f"{j}Self{tag}CI", ci(*g["self"]["ci_clopper_pearson"], unit="pct"))
        mac(f"{j}Self{tag}K", str(g["self"]["k"]))
        mac(f"{j}FA{tag}K", str(g["false_alarm"]["k"]))
        mac(f"{j}Peer{tag}K", str(g["peer"]["k"]))
        mac(f"{j}NonSelf{tag}K", str(g["nonself"]["k"]))
        mac(f"{j}NonSelf{tag}P", "$" + pval(g["nonself"]["p_exact_two_sided"]) + "$")
        w = g["weighted"]["additive"]
        mac(f"{j}AdjAdv{tag}", pp(w["adv"]))
        mac(f"{j}AdjAdv{tag}CI", ci(*w["ci_cluster"]))
    mac(f"PeerDeff{tag}", f"{S[cond]['icc']['peer_deff']:.2f}")
    mac(f"PeerNeff{tag}", f"{S[cond]['icc']['peer_n_eff']:.0f}")
mac("GrokSelfLineupHolm", "$" + pval(S["lineup"]["per_judge"]["Grok"]["self"]["p_holm"]) + "$")
mm = S["lineup"]["mixed_model"]["per_judge"]
for j, g in mm.items():
    key = [k for k in g if "or" == k.lower()]
    if key:
        mac(f"{j}MixedORLineup", f"{g[key[0]]:.2f}")

# Table: every quantity of Section 3, both formats.
BS = "\\"
rows = [BS + "begin{table*}[t]", BS + "centering" + BS + "small" + BS + "setlength" + BS + "tabcolsep{3.5pt}",
        BS + "begin{tabular}{llrrrrrr}", BS + "toprule",
        "Format & Judge & Self-naming & False alarms & Peer baseline & Self-adv. [95" + BS
        + "% CI] & $p$ (Holm) & Skill-adj. " + BS * 2,
        BS + "midrule"]
for cond, tag in cond_tag.items():
    first = True
    for j, g in S[cond]["per_judge"].items():
        sa = g["self_advantage"]
        rows.append(
            f"{tag if first else ''} & {j} & {g['self']['k']}/38 & {g['false_alarm']['k']}/152 & "
            f"{g['peer']['k']}/152 & {pp(sa['adv'])} {ci(*sa['ci_cluster'])} & "
            f"${pval(sa['p_holm_randomization'])}$ & "
            + (pp(g['weighted']['additive']['adv']) if cond == "lineup" else "--") + " " + BS * 2)
        first = False
    rows.append(BS + ("midrule" if cond == "lineup" else "bottomrule"))
rows += [BS + "end{tabular}",
         BS + "caption{Study~1, frontier judges. Self-naming: the judge names itself on its own 38 texts. "
         "False alarms: it names itself on the 152 texts it did not write. Peer baseline: the other four "
         "judges name it on its texts. Self-advantage is the difference in rates, with a prompt-bootstrap "
         "interval; $p$ is the exact within-response randomisation test, Holm-corrected over the five judges. "
         "Skill-adjusted removes each judge's general accuracy and each author's identifiability "
         "(Appendix~" + BS + "ref{app:stats}); it is not interpretable in single-text, where a judge's "
         "accuracy mostly reflects which model it habitually names. In single-text, Gemini, Grok and DeepSeek never name themselves.}",
         BS + "label{tab:frontier}", BS + "end{table*}"]
(Path(__file__).resolve().parent / "table_frontier.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

# ---------------------------------------------------------------------------
# Study 2: open-weight panel (results/revision/openweight/summary.json)
# ---------------------------------------------------------------------------
OW = ROOT / "results" / "revision" / "openweight" / "summary.json"
if OW.exists():
    lines.append("% open-weight panel")
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import ow_numbers  # noqa: E402
    for k, v in ow_numbers.macros(json.loads(OW.read_text())).items():
        mac(k, v)

# Rationale-coder validation: a human annotation if one exists
# (src/rationale_human.py), else the two LLM annotators, said plainly.
RH = ROOT / "results" / "rationale_human.json"
if RH.exists():
    H = json.loads(RH.read_text())
    m_all, m_ho = H["rules_vs_human"]["_micro"], H["rules_vs_human_holdout"]["_micro"]
    ks = sorted(H["rules_vs_human"][c]["kappa"] for c in H["rules_vs_human"]
                if not c.startswith("_") and c != "other"
                and H["rules_vs_human"][c]["kappa"] is not None
                and H["rules_vs_human"][c]["hand_n"] >= 3)
    mac("RationaleValidation",
        f"Against a human annotation of a stratified sample of 150 reasons, made "
        f"blind to judge and author, the rules reach {pct(m_all['precision'], 0)} "
        f"precision and {pct(m_all['recall'], 0)} recall "
        f"(Appendix~\\ref{{app:rationales}}).")
    mac("RationaleHumanAppendix",
        f"A human annotator then labelled the same 150 reasons from the codebook, "
        f"blind to judge, author and both earlier labels. Against the human, the "
        f"rules reach {pct(m_all['precision'])} precision and {pct(m_all['recall'])} "
        f"recall over all 150 and {pct(m_ho['precision'])} and {pct(m_ho['recall'])} "
        f"on the 50 held out (per-category $\\kappa$ {ks[0]:.2f}--{ks[-1]:.2f} for "
        f"categories with at least three human labels); the two LLM annotators "
        f"reach {pct(H['a1_vs_human']['_micro']['f1'])} and "
        f"{pct(H['a2_vs_human']['_micro']['f1'])} F1 against the human.")
else:
    mac("RationaleValidation",
        "Two LLM annotators labelled a stratified sample of 150 reasons from the "
        "codebook alone; the rules agree with the blind one at 97\\% precision and "
        "96\\% recall (Appendix~\\ref{app:rationales}).")
    mac("RationaleHumanAppendix", "")

# Study 1 at scale: the same five frontier judges on an all-API corpus of
# 120 prompts in four genres (results/revision/frontier/summary_api120.json).
FXS = ROOT / "results" / "revision" / "frontier" / "summary_api120.json"
FX_JUDGES = ["GPT", "Claude", "Gemini", "Grok", "DeepSeek"]
if FXS.exists():
    FX = json.loads(FXS.read_text())
    tab = [r"\begin{table}[t]", r"\centering\small", r"\setlength\tabcolsep{2.5pt}",
           r"\resizebox{\columnwidth}{!}{%", r"\begin{tabular}{l rrr rr}", r"\toprule",
           r"Judge & Self & Peer & FA & Self-adv. [95\% CI] & Hit$-$FA \\", r"\midrule"]
    for cond, tag in (("lineup", "Lineup"), ("single", "Single")):
        if cond not in FX:
            continue
        S_ = FX[cond]
        mac(f"FX{tag}Acc", pct(S_["accuracy"]))
        top2 = sorted(S_["blame_share"].values(), reverse=True)[:2]
        mac(f"FX{tag}TopTwo", pct(sum(top2)))
        if cond == "single" and "lineup" in FX:
            tab.append(r"\midrule")
        if cond == "single":
            tab.append(r"\multicolumn{6}{l}{\emph{One text at a time}} \\")
        for j in FX_JUDGES:
            g = S_["judges"].get(j, {})
            if "self_rate" not in g:
                continue
            star = "$^{*}$" if g.get("perm_p_holm", 1) < 0.05 else ""
            dstar = "$^{*}$" if g.get("disc_p_holm", 1) < 0.05 else ""
            mac(f"FX{j}{tag}Self", pct(g["self_rate"]))
            mac(f"FX{j}{tag}Peer", pct(g["peer_baseline"]))
            mac(f"FX{j}{tag}FA", pct(g["false_alarm"]))
            mac(f"FX{j}{tag}Adv", pp(g["self_advantage"]))
            mac(f"FX{j}{tag}AdvCI", ci(*g["adv_ci95"]))
            mac(f"FX{j}{tag}Holm", "$" + pval(max(g["perm_p_holm"], 1e-4)) + "$"
                if g["perm_p_holm"] > 0 else r"$<0.001$")
            mac(f"FX{j}{tag}Disc", pp(g["hit_minus_fa"]))
            mac(f"FX{j}{tag}DiscHolm", "$" + pval(max(g["disc_p_holm"], 1e-4)) + "$"
                if g["disc_p_holm"] > 0 else r"$<0.001$")
            mac(f"FX{j}{tag}NamesSelf", pct(g["names_self_share"]))
            tab.append(" & ".join([j, pct(g["self_rate"]), pct(g["peer_baseline"]),
                                   pct(g["false_alarm"]),
                                   f"{pp(g['self_advantage'])}{star} {ci(*g['adv_ci95'])}",
                                   pp(g["hit_minus_fa"]) + dstar]) + r" \\")
        for gname, G in S_.get("by_genre", {}).items():
            for j, g in G["judges"].items():
                if "self_advantage" in g:
                    mac(f"FX{j}{tag}{gname.capitalize()}Adv", pp(g["self_advantage"]))
                    mac(f"FX{j}{tag}{gname.capitalize()}Disc", pp(g["hit_minus_fa"]))
    tab += [r"\bottomrule", r"\end{tabular}}",
            r"\caption{Study~1 at scale: the five frontier judges on 600 texts the same "
            r"five models wrote through the API for 120 prompts in four genres (120 own "
            r"texts per judge). Columns as in Table~\ref{tab:frontier}; "
            r"$^{*}$Holm-corrected within-prompt permutation $p<0.05$.}",
            r"\label{tab:frontier120}", r"\end{table}"]
    (Path(__file__).resolve().parent / "table_frontier120.tex").write_text(
        "\n".join(tab) + "\n", encoding="utf-8")
    if "single" in FX:
        mac("FXSingleSentence",
            r"One text at a time (3,000 judgments), the judges again send "
            r"\FXSingleTopTwo{} of their guesses to GPT or Claude. GPT names itself "
            r"on \FXGPTSingleNamesSelf{} of all texts, whoever wrote them, which earns "
            r"it a significant self-advantage (\FXGPTSingleAdv{}, Holm "
            r"$p$~\FXGPTSingleHolm{}) with no discrimination at all "
            r"(\FXGPTSingleDisc{}); Claude names itself on few texts but mostly on "
            r"its own (hit minus false-alarm rate \FXClaudeSingleDisc{}).")

# The same comparison split by prompt set: Study 1's 38 prompts re-collected
# through the API, and the 82 new prompts (src/revision/api120_subsets.py).
FXSUB = ROOT / "results" / "revision" / "frontier" / "api120_subsets.json"
if FXSUB.exists():
    for cond, D in json.loads(FXSUB.read_text()).items():
        tag = {"lineup": "Lineup", "single": "Single"}[cond]
        for key, pre in (("study1_prompts_via_api", "FXOld"), ("new_prompts_only", "FXNew")):
            S_ = D[key]
            mac(f"{pre}{tag}Acc", pct(S_["accuracy"]))
            advs = []
            for j, g in S_["judges"].items():
                if "self_rate" not in g:
                    continue
                advs.append(abs(g["self_advantage"]))
                mac(f"{pre}{j}{tag}Self", pct(g["self_rate"]))
                mac(f"{pre}{j}{tag}Peer", pct(g["peer_baseline"]))
                mac(f"{pre}{j}{tag}FA", pct(g["false_alarm"]))
                mac(f"{pre}{j}{tag}Adv", pp(g["self_advantage"]))
                mac(f"{pre}{j}{tag}Holm", "$" + pval(max(g["perm_p_holm"], 1e-4)) + "$"
                    if g["perm_p_holm"] > 0 else r"$<0.001$")
                mac(f"{pre}{j}{tag}Disc", pp(g["hit_minus_fa"]))
                mac(f"{pre}{j}{tag}DiscHolm", "$" + pval(max(g["disc_p_holm"], 1e-4)) + "$"
                    if g["disc_p_holm"] > 0 else r"$<0.001$")
            if advs:
                mac(f"{pre}{tag}MaxAbsAdv", f"{100 * max(advs):.0f}")

# The standard test against the paper's test, in every judge-setting
# (src/revision/standard_vs_proper.py), and the summary table.
SVP = ROOT / "results" / "revision" / "standard_vs_proper.json"
if SVP.exists():
    V = json.loads(SVP.read_text())
    mac("SVPCells", str(V["cells"]))
    mac("SVPStd", str(V["standard_positive"]))
    mac("SVPProper", str(V["proper_positive"]))
    mac("SVPFalse", str(V["standard_false_positive"]))
    mac("SVPFalsePct", pct(V["standard_false_positive"] / V["standard_positive"], 0))
    mac("SVPMissed", str(V["standard_missed"]))
    order, flags, conf = [], {}, {}
    for r in V["rows"]:
        s = r["setting"]
        if s not in flags:
            order.append(s)
            flags[s], conf[s] = [], []
        if r["standard"]:
            flags[s].append(r["judge"])
        if r["proper"]:
            conf[s].append(r["judge"])
    label = {"frontier chat-app, lineup": "Frontier, chat app, lineup",
             "frontier chat-app, single text": "Frontier, chat app, single",
             "frontier API, lineup": "Frontier, API, lineup",
             "frontier API, single text": "Frontier, API, single",
             "open-weight, lineup": "Open-weight, lineup",
             "open-weight, single text": "Open-weight, single",
             "open-weight, yes/no": "Open-weight, yes/no"}
    tab = [r"\begin{table}[t]", r"\centering\small", r"\setlength\tabcolsep{3pt}",
           r"\begin{tabular}{lll}", r"\toprule",
           r"Setting & Standard test & Our test \\", r"\midrule"]
    for s in order:
        tab.append(f"{label.get(s, s)} & {', '.join(flags[s]) or '--'} & "
                   f"{', '.join(conf[s]) or '--'}" + r" \\")
    tab += [r"\midrule",
            f"Judge-settings flagged & {V['standard_positive']} of {V['cells']} & "
            f"{V['proper_positive']} of {V['cells']}" + r" \\",
            r"\bottomrule", r"\end{tabular}",
            r"\caption{Which judges ``recognise themselves''. Standard test: the judge "
            r"names itself on its own text more often than chance (Holm-corrected "
            r"binomial test; for yes/no, says yes to its own text more than half the "
            r"time). Our test: it beats its peers on its own text \emph{and} names "
            r"itself more on its own text than on others' (both Holm-corrected "
            r"permutation tests; for yes/no, AUC above 0.5). Nine judges, three corpora, "
            r"three formats.}",
            r"\label{tab:verdicts}", r"\end{table}"]
    (Path(__file__).resolve().parent / "table_verdicts.tex").write_text(
        "\n".join(tab) + "\n", encoding="utf-8")

# Quality covariate for Study 1: the open-weight panel's ratings of the
# frontier corpus (src/revision/quality_frontier.py).
QF = ROOT / "results" / "revision" / "quality_frontier.json"
if QF.exists():
    Q = json.loads(QF.read_text())
    mac("QFRaterRho", f"{Q['rater_mean_spearman']:.2f}")
    qa = Q["mean_quality_by_author"]
    mac("QFMeanLo", f"{min(qa.values()):.2f}")
    mac("QFMeanHi", f"{max(qa.values()):.2f}")
    for cond, tag in cond_tag.items():
        for j, g in Q[cond].items():
            c = g["claims_vs_quality"]
            if "perm_p" in c:
                mac(f"QF{j}{tag}ClaimP", "$" + pval(c["perm_p"]) + "$")
                mac(f"QF{j}{tag}ClaimDiff", f"{c['qz_claimed_minus_not']:+.2f}".replace("-", "$-$"))
            a = g["advantage_given_quality"]
            if "or_self" in a and a["or_self"] > 0:
                mac(f"QF{j}{tag}OR", f"{a['or_self']:.2f}")
                mac(f"QF{j}{tag}ORP", "$" + pval(a["p_self"]) + "$")
        ps = [g["claims_vs_quality"]["perm_p"] for g in Q[cond].values()
              if "perm_p" in g["claims_vs_quality"]]
        if ps:
            mac(f"QF{tag}ClaimMinP", "$" + pval(min(ps)) + "$")

# On-policy design and the resampled variant: described only once its run
# is complete for all four judges.
_S2 = json.loads(OW.read_text()) if (OW := ROOT / "results" / "revision" / "openweight"
                                      / "summary.json").exists() else {}
_res = _S2.get("onpolicy_resample", {}).get("judges", {})
if len(_res) == 4 and all("auc" in g for g in _res.values()):
    mac("OnPolDesign",
        r"Two \emph{on-policy} variants follow \citet{khullar2026selfattribution}: "
        r"the judge first answers the prompt in the conversation and is then asked "
        r"the yes/no question about a candidate answer, which is either its own "
        r"turn verbatim or a peer's answer (\emph{on-policy}), or its own separate "
        r"corpus answer versus a peer's, with a fresh sample as its own turn "
        r"(\emph{resampled}). The last asks whether having its own writing for the "
        r"task in view helps a judge recognise a different sample of its writing, "
        r"the generative-match account made explicit.")
    mac("OnPolSecondSample", ", and a second, independent answer to every prompt "
        "serves as the judge's own turn in the resampled condition")
    mac("OnPolResampled",
        r"When the judge's own turn is instead a fresh sample and the candidate "
        r"is its separate answer to the same task (\emph{resampled}), the "
        r"verdict splits by judge. Qwen and Phi tell their other sample from "
        r"peers' answers (AUC \OWQwenOnPolResAUC{} and \OWPhiOnPolResAUC{}); "
        r"Llama and Mistral are reliably \emph{below} chance "
        r"(\OWLlamaOnPolResAUC{} and \OWMistralOnPolResAUC{}, Holm "
        r"$p\leq$~\OWMistralOnPolResAUCHolm{}), less willing to claim a second "
        r"answer of their own than a peer's. Having its own answer to the task in "
        r"view, the explicit form of generative match, helps two judges and "
        r"misleads the other two; asked in a fresh context, none of the four "
        r"exceeds chance.")
else:
    mac("OnPolDesign",
        r"An \emph{on-policy} variant follows \citet{khullar2026selfattribution}: "
        r"the judge first answers the prompt in the conversation and is then asked "
        r"the yes/no question about a candidate answer, which is either its own "
        r"turn verbatim or a peer's answer.")
    mac("OnPolResampled", "")
    mac("OnPolSecondSample", "")

# Study 2 classifier (src/revision/classifier_ow.py).
OWC = ROOT / "results" / "revision" / "openweight" / "classifier.json"
if OWC.exists():
    for k, v in json.loads(OWC.read_text()).items():
        t = {"crosssample": "CrossSample"}.get(k, k.capitalize())
        mac(f"OWClf{t}", pct(v["accuracy"]))
        mac(f"OWClf{t}CI", ci(*v["ci95"], unit="pct"))

# Study 1 discrimination (hit minus false-alarm rate, within-lineup
# permutation): results/revision/frontier_discrimination.json.
FD = ROOT / "results" / "revision" / "frontier_discrimination.json"
if FD.exists():
    for cond, tag in cond_tag.items():
        for j, g in json.loads(FD.read_text())[cond].items():
            if g:
                mac(f"{j}Disc{tag}", pp(g["hit_minus_fa"]))
                mac(f"{j}DiscLOR{tag}", f"{g['log_or']:.2f}".replace("-", "$-$"))
                mac(f"{j}Disc{tag}Holm", "$" + pval(max(g["disc_p_holm"], 1 / 4000)) + "$"
                    if g["disc_p_holm"] > 0 else r"$<0.001$")

# The submitted study's macros (paper/numbers.tex, read before this file)
# print negatives with a hyphen; restate those with a typeset minus.
import re  # noqa: E402
for name, val in re.findall(r"\\newcommand\{\\(\w+)\}\{(-[\d.]+)\}",
                            (ROOT / "paper" / "numbers.tex").read_text(encoding="utf-8")):
    lines.append(rf"\renewcommand{{\{name}}}{{$-${val[1:]}}}")

OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(lines) - 2} macros)")
