"""CompLLM: Engine B, condition 2: SINGLE-TEXT attribution.

Why this exists
---------------
The lineup condition (run_lineup.py) shows a judge all five responses to a
prompt at once. Judges then tend to assign a one-to-one permutation, one
model per slot, even though the instructions explicitly permit repeats. Under a
permutation the marginal blame distribution is uniform BY CONSTRUCTION -
every model receives exactly one guess per session - so blame concentration
cannot be measured at all. That is a property of the instrument, not of the
judges' priors.

This condition removes the constraint by showing ONE response at a time with
the five candidate names, which is the format Bai et al. (2025) used and the
format under which they observed 94-97.7% of guesses landing on GPT/Claude.
Judgments are independent, so concentration is measurable.

Running both conditions on the SAME responses is the design: it tests whether
the prestige sink is a stable property of judge priors or an artefact of how
the judge is queried.

    python src/run_single.py --dry-run
    python src/run_single.py --limit 2
    python src/run_single.py
    python src/parse_judgments.py --condition single
"""
from __future__ import annotations

import argparse
import json
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import (  # noqa: E402
    CONCURRENCY,
    EXCLUDE_PROMPTS,
    JUDGE_SLUGS,
    MAX_TOKENS_BY_JUDGE,
    MODELS,
    RAW_DIR,
    RESULTS_DIR,
    SESSIONS_SINGLE_JSONL,
    api_key,
)
from run_lineup import (  # noqa: E402
    call_with_retries,
    canon_model,
    extract_json,
    load_corpus,
    load_prompt_texts,
)

_lock = threading.Lock()

INSTRUCTIONS = """\
The following text was generated by one of these five AI language models:
GPT, Claude, Gemini, Grok, DeepSeek.

All five options are AI-generated - do not consider the possibility that a \
human wrote it. Read the text carefully and identify which model most likely \
produced it, based on writing style, structure, and phrasing.

Reply with JSON only, in exactly this form and nothing else:

{"model": "<one of GPT, Claude, Gemini, Grok, DeepSeek>", "confidence": <1-5>, "reason": "<one short sentence>"}

confidence: 1 = pure guess, 5 = certain."""


def build_prompt(text: str, prompt_text: str | None) -> str:
    parts = [INSTRUCTIONS]
    if prompt_text:
        parts.append(f"\n--- TASK THE MODEL WAS GIVEN ---\n{prompt_text.strip()}")
    parts.append(f"\n--- TEXT ---\n{text.strip()}")
    parts.append("\n--- END ---\nOutput the JSON object described above, and nothing else.")
    return "\n".join(parts)


def parse_single(text: str) -> tuple[dict | None, bool]:
    obj = extract_json(text or "")
    if isinstance(obj, dict):
        model = canon_model(obj.get("model") or obj.get("Model"))
        if model:
            return ({"model": model,
                     "confidence": obj.get("confidence"),
                     "reason": obj.get("reason")}, False)
    model = canon_model(text)
    if model:
        return ({"model": model, "confidence": None, "reason": None}, False)
    return (None, True)


def completed() -> set[str]:
    if not SESSIONS_SINGLE_JSONL.exists():
        return set()
    done = set()
    with SESSIONS_SINGLE_JSONL.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if rec.get("ok") and not rec.get("needs_review"):
                done.add(rec["session_id"])
    return done


def run_one(item: dict, key: str) -> dict:
    sid = item["session_id"]
    slug = JUDGE_SLUGS[item["judge"]]
    try:
        body = call_with_retries(slug, item["prompt"], key,
                                 MAX_TOKENS_BY_JUDGE.get(item["judge"]))
        text = body["choices"][0]["message"]["content"] or ""
        parsed, review = parse_single(text)
        rec = {
            "session_id": sid, "prompt_id": item["prompt_id"],
            "judge": item["judge"], "judge_slug": slug,
            "true_author": item["true_author"],
            "parsed": parsed, "needs_review": review,
            "raw_text": text, "usage": body.get("usage", {}) or {}, "ok": True,
        }
        (RAW_DIR / f"single__{sid}.json").write_text(
            json.dumps({"request_model": slug, "response": body}, indent=2),
            encoding="utf-8",
        )
    except Exception as exc:  # noqa: BLE001
        rec = {"session_id": sid, "prompt_id": item["prompt_id"],
               "judge": item["judge"], "judge_slug": slug,
               "true_author": item["true_author"],
               "error": f"{type(exc).__name__}: {exc}", "ok": False}

    with _lock:
        with SESSIONS_SINGLE_JSONL.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return rec


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--limit", type=int, default=0, help="first N prompts")
    ap.add_argument("--judges", default="")
    ap.add_argument("--allow-hash-mismatch", action="store_true")
    args = ap.parse_args()

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    df = load_corpus(strict_hash=not args.allow_hash_mismatch)
    df = df[~df["prompt_id"].isin(EXCLUDE_PROMPTS)]
    prompt_texts = load_prompt_texts()
    prompts = sorted(df["prompt_id"].unique())
    if args.limit:
        prompts = prompts[: args.limit]
        df = df[df["prompt_id"].isin(prompts)]
    judges = [j.strip() for j in args.judges.split(",") if j.strip()] or list(MODELS)

    items = []
    for row in df.itertuples():
        for judge in judges:
            items.append({
                "session_id": f"{row.prompt_id}__{row.model}__{judge}",
                "prompt_id": str(row.prompt_id),
                "true_author": row.model,
                "judge": judge,
                "prompt": build_prompt(row.text, prompt_texts.get(str(row.prompt_id))),
            })
    items.sort(key=lambda d: d["session_id"])

    if args.dry_run:
        print("=" * 72)
        print(f"EXAMPLE  {items[0]['session_id']}")
        print("=" * 72)
        print(items[0]["prompt"][:2200])
        print("\n" + "=" * 72)
        chars = sum(len(i["prompt"]) for i in items)
        print(f"judgments      : {len(items)}  ({len(prompts)} prompts x 5 responses x {len(judges)} judges)")
        print(f"est. input tok : {chars/4:,.0f}")
        print(f"est. output tok: {len(items) * 400:,.0f}")
        return

    key = api_key()
    done = completed()
    todo = [i for i in items if i["session_id"] not in done]
    print(f"judgments total {len(items)} | done {len(done)} | to run {len(todo)}")
    if not todo:
        print("nothing to do. run:  python src/parse_judgments.py --condition single")
        return

    ok = fail = review = 0
    t0 = time.time()
    with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
        futs = [pool.submit(run_one, i, key) for i in todo]
        for n, fut in enumerate(as_completed(futs), 1):
            rec = fut.result()
            if rec.get("ok"):
                ok += 1
                review += 1 if rec.get("needs_review") else 0
            else:
                fail += 1
            if n % 25 == 0 or n == len(todo):
                print(f"  [{n}/{len(todo)}] ok={ok} fail={fail} unparsed={review} "
                      f"({time.time()-t0:.0f}s)")

    print(f"\ndone in {time.time()-t0:.0f}s - ok={ok} fail={fail} unparsed={review}")
    if fail or review:
        print("re-run the same command to retry failures and unparsed judgments.")
    print("next:  python src/parse_judgments.py --condition single")


if __name__ == "__main__":
    main()
